---
name: Integration

# yamllint disable-line rule:truthy
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-changes:
    name: Check Changes
    runs-on: ubuntu-latest
    outputs:
      python: ${{ steps.filter.outputs.python }}
      hacs: ${{ steps.filter.outputs.hacs }}
      hassfest: ${{ steps.filter.outputs.hassfest }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            python:
              - '**.py'
              - 'requirements*.txt'
              - 'pyproject.toml'
              - '.github/workflows/integration.yaml'
              - '.github/workflows/python-checks.yml'
            hacs:
              - 'hacs.json'
              - 'README.md'
              - 'custom_components/**'
              - '.github/workflows/integration.yaml'
            hassfest:
              - 'custom_components/**'
              - '.github/workflows/integration.yaml'
            frontend:
              - '**.js'
              - '**.ts'
              - 'ts/**'
              - '.eslintrc.cjs'
              - 'package.json'
              - 'rollup.config.js'
              - 'tsconfig.json'
              - 'vitest.config.ts'
              - '.github/workflows/integration.yaml'
              - '.github/workflows/frontend-checks.yml'

  python:
    name: Python
    needs: check-changes
    if: needs.check-changes.outputs.python == 'true'
    uses: ./.github/workflows/python-checks.yml
    secrets: inherit

  hacs:
    name: HACS
    needs: check-changes
    if: needs.check-changes.outputs.hacs == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: HACS Action
        uses: hacs/action@main
        with:
          category: integration

  hassfest:
    name: Hassfest
    needs: check-changes
    if: needs.check-changes.outputs.hassfest == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: home-assistant/actions/hassfest@master

  frontend:
    name: Frontend
    needs: check-changes
    if: needs.check-changes.outputs.frontend == 'true'
    uses: ./.github/workflows/frontend-checks.yml
    secrets: inherit
