---
name: Integration

# yamllint disable-line rule:truthy
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-changes:
    name: Check Changes
    runs-on: ubuntu-latest
    outputs:
      python: ${{ steps.filter.outputs.python }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            python:
              - '**.py'
              - 'requirements*.txt'
              - 'pyproject.toml'
              - '.github/workflows/integration.yaml'
              - '.github/workflows/python-checks.yml'
            frontend:
              - '**.js'
              - '**.ts'
              - 'ts/**'
              - '.eslintrc.cjs'
              - 'package.json'
              - 'rollup.config.js'
              - 'tsconfig.json'
              - 'vitest.config.ts'
              - '.github/workflows/integration.yaml'
              - '.github/workflows/frontend-checks.yml'

  integration:
    name: Integration
    needs: check-changes
    if: needs.check-changes.outputs.python == 'true'
    uses: ./.github/workflows/python-checks.yml
    secrets: inherit

  frontend:
    name: Frontend
    needs: check-changes
    if: needs.check-changes.outputs.frontend == 'true'
    uses: ./.github/workflows/frontend-checks.yml
    secrets: inherit
